# Exceptions and events

## Events

- Notification that something specific has occurred
- Typically asynchronous handled
- Manifest most commonly as GUI events

### Event handling

- Events are generated by asynchronous stimuli
    - Mouse click
    - Mouse motion
    - Key presses
- Often occurs when program is doing something else
- Events **interrupt** normal program processing
- Method invoked on an event is called an **event handler**
- Sometimes called a **callback function**

## Exceptions

- Support for runtime error handling
- Synchronously handled
- Typically two kinds
    - Hardware errors (division by zero, disk read error, overflow errors)
    - Programming errors (null pointer dereference, index out of bounds)
- Can also be defined and used for library classes
    - `pop()` called on an empty stack
    - `push()` called on a full stack

### Error handling in C (no exceptions)

- Originally handled by returning `-1` from a function
- Dedicate control flow case to handle it

```C
switch (n = read(...)) {
    case -1:
        exit(EXIT_FAILURE)
    default:
        exit(EXIT_SUCCESS)
}
```

- Exceptions can be simulated with `setjmp` and `longjmp`
- Nearly every language with exceptions use this technique

```C
static struct jmp_buf buf;
void second(void) {
    printf("second\n");
    longjmp(&buf, 1); // jump back to where setjmp was called - making setjmp now return 1
}

void first(void) {
    second();
    prinf("first\n") // does not print
}

int main() {
    if (!setjmp(&buf)) { // like a try blcok
        first();
    }
    else { // catch block
        printf("main\n");
    }
}
```

### Error handling in C++

- Based on machine language
- Data objects are `thrown()` to a matching `catch()`
- `try` blocks surround guarded instructions
- Exceptions may be of any type (objects or primitives)
- Methods and functions declare what exceptions they throw

```C++
class Vector {
    int* buf;
    int size;
public:
    static const max = 100;
    class BaseException {};
    class RangeException : public BaseException {};
    class SizeException : public BaseException {};
    
    Vector(int newSize) throw(SizeException) {
        if (newSize < 0 || newSize > max) {
            throw SizeException();
        }
        size = newSize;
        buf = new int[newSize];
        for (int i=0; i < newSize; ++i) {
            buf[i] = 2 * i;
        }
    }

    int& operator[] (int i) throw(RangeException) {
        if (i < 0 || i > size) {
            throw RangeException();
        }
        return buf[i];
    }
}

int getInt(char* prompt) {
    std::cout << prompt << ": ";
    int i;
    std::cin >> i;
    if (i < 0) {
        throw "Hello"; // thorws a const char*
    }
    return i;
}

void testException() {
    for (;;) {
        try {
            int size = getInt("Enter a size");
            Vector v1(size);
            int index = getInt("Enter an index");
            std::cout << v1[index];
        }
        catch (Vector::RangeException& e) {
            std::cout << "Index out of bounds\n";
        }
        catch(Vector::SizeException& e) {
            std::cout << "Size out of range 0..max\n";
        }
        catch(...) {
            std::cout << "Got some unknown exception\n";
            throw; // Rethrow the current exception
            // calls unexpected() which calls terminate()
        }
    }
}

int main() {
    while (true) {
        testException();
    }
    catch(Vector::BaseException& e) {
        std::cout << "Got some kind of BaseException\n";
    }
}
```

### Error handling in Java

- Based on C++ exception handling, but does not allow anything to be thrown
- Can only throw subclasses of `Exception` or implementer of the `Throwable` interface
- Adds the `finally` block to the `try-catch` pattern

```Java
try {
    ...
}
catch(...) {
    ...
}
    finally { //executed when leaving normally or handling an exception
    ...
}
```

## Assertions

- Allows declaration of expression believed to be true
- Some languages allow them to be turned on or off
    - Java enables them with a command line option
- Failure of assertions causes an immediate exit